export const consoleTable = {
    "Game Boy": "gb",
    "Game Boy Color": "gbc",
    "Game Boy Advance": "gba",
    "NES/Famicom": "nes",
    "SNES/Super Famicom": "snes",
    "Nintendo 64": "n64",
    "GameCube": "gc",
    "Nintendo DS": "ds",
    "Nintendo DSi": "dsi",
    "Pokemon Mini": "mini",
    "Virtual Boy": "vb",
    "PlayStation": "ps1",
    "PlayStation 2": "ps2",
    "PlayStation Portable": "psp",
    "Atari 2600": "2600",
    "Atari 7800": "7800",
    "Atari Jaguar": "jag",
    "Atari Jaguar CD": "jcd",
    "Atari Lynx": "lynx",
    "SG-1000": "sg1k",
    "Master System": "sms",
    "Game Gear": "gg",
    "Genesis/Mega Drive": "md",
    "Sega CD": "scd",
    "32X": "32x",
    "Saturn": "sat",
    "Dreamcast": "dc",
    "PC Engine/TurboGrafx-16": "pce",
    "PC Engine CD/TurboGrafx-CD": "pccd",
    "PC-8000/8800": "8088",
    "PC-FX": "pc-fx",
    "Neo Geo CD": "ngcd",
    "Neo Geo Pocket": "ngp",
    "3DO Interactive Multiplayer": "3do",
    "Amstrad CPC": "cpc",
    "Apple II": "a2",
    "Arcade": "arc",
    "Arcadia 2001": "a2001",
    "Arduboy": "ard",
    "ColecoVision": "cv",
    "Elektor TV Games Computer": "elek",
    "Fairchild Channel F": "chf",
    "Intellivision": "intv",
    "Interton VC 4000": "vc4000",
    "Magnavox Odyssey 2": "mo2",
    "Mega Duck": "duck",
    "MSX": "msx",
    "Standalone": "exe",
    "Uzebox": "uze",
    "Vectrex": "vect",
    "WASM-4": "wasm4",
    "Watara Supervision": "wsv",
    "Wii": "wii",
    "WonderSwan": "ws"
  };