export const consoleTable = {
    "Game Boy": "gb",
    "Game Boy Color": "gbc",
    "Game Boy Advance": "gba",
    "NES/Famicom": "nes",
    "SNES/Super Famicom": "snes",
    "Nintendo 64": "n64",
    "GameCube": "gc",
    "Nintendo DS": "ds",
    "Nintendo DSi": "dsi",
    "Pokemon Mini": "mini",
    "Virtual Boy": "vb",
    "PlayStation": "ps1",
    "PlayStation 2": "ps2",
    "PlayStation Portable": "psp",
    "Atari 2600": "2600",
    "Atari 7800": "7800",
    "Atari Jaguar": "jag",
    "Atari Jaguar CD": "jcd",
    "Atari Lynx": "lynx",
    "SG-1000": "sg1k",
    "Master System": "sms",
    "Game Gear": "gg",
    "Genesis/Mega Drive": "md",
    "Sega CD": "scd",
    "32X": "32x",
    "Saturn": "sat",
    "Dreamcast": "dc",
    "PC Engine/TurboGrafx-16": "pce",
    "PC Engine CD/TurboGrafx-CD": "pccd",
    "PC-8000/8800": "8088",
    "PC-FX": "pc-fx",
    "Neo Geo CD": "ngcd",
    "Neo Geo Pocket": "ngp",
    "3DO Interactive Multiplayer": "3do",
    "Amstrad CPC": "cpc",
    "Apple II": "a2",
    "Arcade": "arc",
    "Arcadia 2001": "a2001",
    "Arduboy": "ard",
    "ColecoVision": "cv",
    "Elektor TV Games Computer": "elek",
    "Fairchild Channel F": "chf",
    "Intellivision": "intv",
    "Interton VC 4000": "vc4000",
    "Magnavox Odyssey 2": "mo2",
    "Mega Duck": "duck",
    "MSX": "msx",
    "Standalone": "exe",
    "Uzebox": "uze",
    "Vectrex": "vect",
    "WASM-4": "wasm4",
    "Watara Supervision": "wsv",
    "Wii": "wii",
    "WonderSwan": "ws"
  };

export const consoleTableId = {
  1: "md",
  2: "n64",
  3: "snes",
  4: "gb",
  5: "gba",
  6: "gbc",
  7: "nes",
  8: "pce",
  9: "scd",
  10: "32x",
  11: "sms",
  12: "ps1",
  13: "lynx",
  14: "ngp",
  15: "gg",
  16: "gc",
  17: "jag",
  18: "ds",
  19: "wii",
  21: "ps2",
  23: "mo2",
  24: "mini",
  25: "2600",
  27: "arc",
  28: "vb",
  29: "msx",
  33: "sg1k",
  37: "cpc",
  38: "a2",
  39: "sat",
  40: "dc",
  41: "psp",
  43: "3do",
  44: "cv",
  45: "intv",
  46: "vect",
  47: "8088",
  49: "pc-fx",
  51: "7800",
  53: "ws",
  56: "ngcd",
  57: "chf",
  63: "wsv",
  69: "duck",
  71: "ard",
  72: "wasm4",
  73: "a2001",
  74: "vc4000",
  75: "elek",
  76: "pccd",
  77: "jcd",
  78: "dsi",
  80: "uze",
  81: "fds",
  102: "exe"
};